#DiscordSRVUtils addon config:

#Bot prefix used in the discord server
# for example, ! then the commands start with !, so !help !createticket
BotPrefix: "!"

#MySQL settings
MySQL:
  #Should we use MySQL?
  isEnabled: false
  #Username used to login
  UserName: "root"
  #Password used to login
  Password: "password"
  #Name of database
  Database: "DiscordSRVUtilsData"
  #Host to connect to database. Sometimes Maybe called address in panels.
  Host: "localhost"
  #Port. The last thin in the host. If you have ":3306" at the end of your host (any number after :) remove : and the number and put them here
  Port: 3306

#MySQL won't work properly until you restart.

#welcomer_channel. This channel will contain welcome message for people who join the discord server
welcomer_channel: 000000000000000000

#welcomer_message. We will send this message when a discord user joins
#Avaiable PlaceHolders: [User_Name], [User_Tag], [User_Mention].
welcomer_message:
  - "ðŸ”¸ **Welcome [User_Name] To The server!**"
  - ""
  - ""
  - "ðŸ”¸ **Server ip** | play.example.com"
  - ""
  - ""
  - "ðŸ”¸ **Store** | store.example.com"

#mc_welcomer_message. This message will be send to online players when a new member joins the discord server
#Avaible PlaceHolders: [User_name], [User_Tag], [Guild_Name].
mc_welcomer_message: "&b[User_Name] &aJoined the Discord server"

#Should we send the message above to all players when a new member joins the discord server?
#Set to true if you want the message to be send, false if you don't
join_message_to_online_players: true


#What is the embed color we should use for the welcomer embed?
#Default: RED
welcomer_message_embed_color: RED

#Should we send the afk messages to discord?
essentials_afk_to_discord: true

#Message to be send when player is afk
#Avaible PlaceHolders: [Player_Name], [Player_DisplayName]
essentials_player_afk_message:
  - "**[Player_Name] is now afk**"

#Message to send when player is no longer afk
#Avaible PlaceHolders: [Player_Name], [Player_DisplayName]
essentials_player_no_longer_afk_message:
  - "**[Player_Name] is no longer afk**"


#ADVANCEDBAN

#Should we punish the player who gets banned in minecraft ti discord
advancedban_punishments_to_discord: true

#Should we send the message of player banned to discord?
advancedban_ban_message_to_discord: true

#Message to send when player is banned
#Avaible placeholders: [Player], [Operator], [Reason]
advancedban_ban_message:
  - "**[Player] has been banned by [Operator]**"
  - "**For the reason [Reason]**"

#Should we send the temp bans messages to discord?
advancedban_temp_ban_message_to_discord: true

#Message to send when player is temp banned
#Avaible placeholders: [Player], [Operator] [Reason], [Duration]
advancedban_temp_ban_message:
  - "**[Player] was banned by [Operator]**"
  - "**For the reason [Reason]**"
  - "**This player got banned for [Duration]**"

#Should we send the ip ban message to discord when player is banned?
advancedban_ip_ban_message_to_discord: true

#The message that will be send when player is ip banned
#Avaible placeholders: [Player], [Operator], [Reason]
advancedban_ip_ban_message:
  - "**[Player] was banned by [Operator]**"
  - "**For the reason [Reason]**"

#Should we send the ip ban message to discord?
advancedban_temp_ip_ban_message_to_discord: true

#Message to be send when player is temp ip banned
#Avaible placeholders: [Player], [Operator] [Reason], [Duration]
advancedban_temp_ip_ban_message:
  - "**[Player] was banned by [Operator]**"
  - "**For the reason [Reason]**"
  - "**This player got banned for [Duration]**"

#Should we send the message to discord when player is muted?
advancedban_mute_message_to_discord: true

#Role to add to user when muted or temp muted.
muted_role: 000000000000000000

#Message to be send when player is muted in game
#Avaible placeholders: [Player], [Operator], [Reason]
advancedban_mute_message:
  - "**[Player] has been muted by [Operator]**"
  - "**For the reason [Reason]**"

#Should we send the message of temp mutes to discord?
advancedban_temp_mute_message_to_discord: true

#Message to be send when player is temp muted in game
#Avaible placeholders: [Player], [Operator] [Reason], [Duration]
advancedban_temp_mute_message:
  - "**[Player] has been muted by [Operator]**"
  - "**For the reason [Reason]**"
  - "**This player is muted for [Duration]**"

#Should we punish the player on discord when punished in game?
advancedban_unpunishments_to_discord: true

#WARNING: if player is not on the server, the plugin wont be able to punish

#Should we send a message when player is unbanned?
advancedban_unban_to_discord: true

#Message to send when player is unbanned
#Avaible placeholders: [Player], [Operator]
advancedban_unban_message:
  - "**[Player] has been unbanned by [Operator]**"


#Should we send a message when player is un temp banned from discord?
advancedban_untempban_to_discord: true

#Message to send when player is untemp banned
#Avaible placeholders: [Player], [Operator]
advancedban_untempban_message:
  - "**[Player] has been unbanned by [Operator]**"

#Should we send the player untemp ip banned message to discord?
advancedban_untempipban_to_discord: true

#Message to send when player is untemp ip banned.
#Avaible placeholders: [Player], [Operator]
advancedban_untempipban_message:
  - "**[Player] has been unbanned by [Operator]**"

#Should we send the player unip banned message to discord?
advancedban_unipban_to_discord: true

#Message to send when player is unip banned.
#Avaible placeholders: [Player], [Operator]
advancedban_unipban_message:
  - "**[Player] has been unbanned by [Operator]**"

#Should we send a message on discord when player is unmuted?
advancedban_unmute_message_to_discord: true

#Message to send when player is unmuted.
#Avaible placeholders: [Player], [Operator]
advancedban_unmute_message:
  - "**[Player] was unmuted by [Operator]**"

#Should we send a message when player is un temp muted to discord?
advancedban_untempmute_message_to_discord: true

advancedban_untempmute_message:
  - "**[Player] has been unbanned by [Operator]"




#Bot status. can be set to ONLINE, DND, IDLE.
bot_status: ONLINE


#Reaction roles, tickets, Role saver and databases and more coming soon.